basePath: /v1
definitions:
  http.DefaultResponse-error:
    properties:
      data: {}
      error_message:
        type: string
      status:
        type: string
    type: object
  http.DefaultResponse-string:
    properties:
      data:
        type: string
      error_message:
        type: string
      status:
        type: string
    type: object
  http.confirmRequest:
    properties:
      otp_code:
        type: string
      username:
        type: string
    required:
    - otp_code
    - username
    type: object
  http.registerRequest:
    properties:
      first_name:
        type: string
      last_name:
        type: string
      password:
        maxLength: 32
        minLength: 8
        type: string
      username:
        maxLength: 32
        minLength: 3
        type: string
    required:
    - first_name
    - last_name
    - password
    - username
    type: object
host: assyl-c9b2197f0ace.herokuapp.com
info:
  contact: {}
  description: API для работы с приложением для ЖК.
  title: Assyl Backend API
  version: "1.0"
paths:
  /auth/confirm:
    post:
      consumes:
      - application/json
      description: Подтверждает пользователя по OTP-коду.
      parameters:
      - description: Confirm request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/http.confirmRequest'
      produces:
      - application/json
      responses:
        "204":
          description: Подтверждение прошло успешно
        "400":
          description: Невалидный запрос
          schema:
            $ref: '#/definitions/http.DefaultResponse-error'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/http.DefaultResponse-error'
      summary: Confirm registration
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Регистрирует нового пользователя и отправляет OTP на указанный
        username (телефон/почта).
      parameters:
      - description: Register request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/http.registerRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Успешная регистрация
          schema:
            $ref: '#/definitions/http.DefaultResponse-string'
        "400":
          description: Невалидный запрос
          schema:
            $ref: '#/definitions/http.DefaultResponse-error'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/http.DefaultResponse-error'
      summary: Register new user
      tags:
      - auth
swagger: "2.0"
